package com.example.mbankingapp.ui.theme

const val AccountName = "Account Name"
const val AccountNumber = "Account Number"
const val AccountDetail = "Account Detail"
const val CompanyName = "Company Name"
const val Data = "data"
const val Status ="status"
const val Summ = "summ"
const val Account = "Account"
const val RecentTransactions = "Recent Transactions"
const val ViewAll = "VIEW ALL"
const val Add = "Add"

const val Transaction = "transaction"
const val TrApplied = "trApplied"
const val TrApllEditText = "trApplEditText"
const val TrNumber = "trNumber"
const val TrNumberEditText = "trNumberEditText"
const val TrDate ="trDate"
const val DateEditText = "dateEditText"
const val TrStatus = "trStatus"
const val TrStatusEditText = "trStatusEditText"
const val Amount = "amount"
const val AmountEditText = "amountEditText"
const val ButtonOkay = "buttonOkay"